---
- hosts: mysql
  become: yes

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Create dynamic MySQL variables.
      set_fact:
        mysql_users:
          - name: demo-rails-app
            host: "{{ groups['railsapp'][0] }}"
            password: demo-rails-app
            priv: "*.*:ALL"
          - name: demo-rails-app
            host: "{{ groups['railsapp'][1] }}"
            password: demo-rails-app
            priv: "*.*:ALL"

  roles:
    - geerlingguy.mysql