---
- hosts: mysql
  become: yes

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Create dynamic MySQL variables.
      set_fact:
        mysql_users:
          - name: mycompany_user
            host: "{{ groups['mysql'][0] }}"
            password: secret
            priv: "*.*:SELECT"
  roles:
    - geerlingguy.mysql